export const endpoints = {
  products: '/api/products',
  sellerProducts: '/api/seller/products',
  productDetail: (id: string | number) => `/api/products/${id}`,
  setups: '/api/setups',
  setupDetail: (id: string | number) => `/api/setups/${id}`,
  homePopularProducts: '/api/home/popular-products',
  homePopularSetups: '/api/home/popular-setups',
  cart: '/api/cart',
  cartItems: '/api/cart/items',
  addresses: '/api/addresses',
  addressDetail: (id: string | number) => `/api/addresses/${id}`,
  orders: '/api/orders',
  orderDetail: (id: string | number) => `/api/orders/${id}`,
  orderStatus: (id: string | number) => `/api/orders/${id}/status`,
  orderCancel: (id: string | number) => `/api/orders/${id}/cancel`,
  tossConfirm: '/api/payments/toss/confirm',
}
